#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined, meta, nodes
from jinja2.visitor import NodeVisitor


REPO_ROOT = Path(__file__).resolve().parents[3]
AI_SYNC_ROOT = REPO_ROOT / "tools" / "ai-sync"
TEMPLATE_ROOT = AI_SYNC_ROOT / "templates"
REGISTRY_PATH = AI_SYNC_ROOT / "registry.yaml"
OPERATIONS_PATH = AI_SYNC_ROOT / "operations.yaml"
ADAPTERS_DIR = AI_SYNC_ROOT / "adapters"
RUNTIMES_DIR = AI_SYNC_ROOT / "runtimes"

GENERATED_NOTICE = (
    "<!-- Generated by tools/ai-sync/scripts/render.py from "
    "tools/ai-sync/*.yaml and tools/ai-sync/templates/. Do not edit directly. -->"
)

CATEGORY_ORDER = [
    "planning",
    "execution",
    "testing",
    "verification",
    "cleanup",
    "state",
]

PLACEHOLDER_RE = re.compile(
    r"\{([A-Za-z_][A-Za-z0-9_]*)(?::([A-Za-z_][A-Za-z0-9_]*))?\}"
)


@dataclass(frozen=True)
class RenderedFile:
    template: str
    output: Path
    content: str


class FilterCollector(NodeVisitor):
    def __init__(self) -> None:
        self.filters: set[str] = set()

    def visit_Filter(self, node: nodes.Filter) -> None:  # noqa: N802 - jinja visitor API
        self.filters.add(node.name)
        self.generic_visit(node)


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise SystemExit(f"{path.relative_to(REPO_ROOT)} must contain a mapping")
    return data


def load_named_yaml(directory: Path, key: str) -> dict[str, dict[str, Any]]:
    loaded: dict[str, dict[str, Any]] = {}
    for path in sorted(directory.glob("*.yaml")):
        data = load_yaml(path)
        name = data.get(key)
        if not isinstance(name, str):
            raise SystemExit(f"{path.relative_to(REPO_ROOT)} must declare `{key}`")
        if name in loaded:
            raise SystemExit(f"Duplicate {key} `{name}`")
        loaded[name] = data
    if not loaded:
        raise SystemExit(f"No {key} files found in {directory.relative_to(REPO_ROOT)}")
    return loaded


def active_improvements(registry: dict[str, Any]) -> list[dict[str, Any]]:
    improvements = registry.get("improvements", [])
    if not isinstance(improvements, list):
        raise SystemExit("registry.yaml improvements must be a list")
    return [item for item in improvements if item.get("status") == "active"]


def by_category(rule: dict[str, Any]) -> int:
    try:
        return CATEGORY_ORDER.index(rule["category"])
    except ValueError:
        return len(CATEGORY_ORDER)


def rules_for(
    registry: dict[str, Any],
    runtime: str,
    phase: str | None = None,
    categories: list[str] | None = None,
) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for rule in active_improvements(registry):
        applies_to = rule.get("applies_to", {})
        runtimes = applies_to.get("runtimes", [])
        phases = applies_to.get("phases", [])
        if runtime not in runtimes:
            continue
        if phase is not None and phase not in phases:
            continue
        if categories is not None and rule.get("category") not in categories:
            continue
        selected.append(rule)
    selected.sort(key=lambda item: (by_category(item), item["id"]))
    return selected


def runtime_notes(rule: dict[str, Any], runtime: str) -> str:
    mapping = rule.get("runtime_mapping", {}).get(runtime, {})
    notes = mapping.get("notes", [])
    if not notes:
        return rule.get("policy", "").strip()
    return " ".join(note.strip() for note in notes)


def render_rule_list(
    registry: dict[str, Any],
    runtime: str,
    phase: str,
    categories: list[str] | None = None,
) -> str:
    rules = rules_for(registry, runtime, phase=phase, categories=categories)
    if not rules:
        return "- None."
    return "\n".join(
        f"- `[{rule['category']}]` `{rule['id']}` {runtime_notes(rule, runtime)}"
        for rule in rules
    )


def render_active_rules_table(registry: dict[str, Any]) -> str:
    lines = [
        "| Rule ID | Category | Summary |",
        "|---------|----------|---------|",
    ]
    for rule in active_improvements(registry):
        lines.append(f"| `{rule['id']}` | {rule['category']} | {rule['summary']} |")
    return "\n".join(lines)


def render_registry_reference(registry: dict[str, Any]) -> str:
    lines: list[str] = []
    for rule in active_improvements(registry):
        lines.append(f"### {rule['id']} - {rule['title']}")
        lines.append("")
        lines.append(f"**Category:** {rule['category']}")
        lines.append("")
        lines.append(f"**Policy:** {rule['policy']}")
        lines.append("")
        lines.append("**Runtime notes:**")
        for runtime in rule.get("applies_to", {}).get("runtimes", []):
            lines.append(f"- `{runtime}`: {runtime_notes(rule, runtime)}")
        lines.append("")
    return "\n".join(lines).rstrip()


def resolve_validator(
    operations: dict[str, Any], adapter: dict[str, Any], validator_name: str
) -> dict[str, Any]:
    shared = operations.get("shared_validators", {})
    adapter_validators = adapter.get("validators", {})
    if validator_name in shared:
        return shared[validator_name]
    if validator_name in adapter_validators:
        return adapter_validators[validator_name]
    raise SystemExit(
        f"Adapter `{adapter['adapter']}` does not define validator `{validator_name}`"
    )


def normalize_value(value: str, validator: dict[str, Any]) -> str:
    normalizer = validator.get("normalize")
    if normalizer is None:
        return value
    if normalizer == "strip_leading_hash":
        return value[1:] if value.startswith("#") else value
    raise ValueError(f"Unknown normalizer `{normalizer}`")


def validate_value(
    operations: dict[str, Any],
    adapter: dict[str, Any],
    validator_name: str,
    value: Any,
) -> Any:
    validator = resolve_validator(operations, adapter, validator_name)
    runtime_type = validator.get("runtime_type")
    if runtime_type == "list":
        if not isinstance(value, list) or not value:
            raise ValueError(f"`{validator_name}` must be a non-empty list")
        item_validator = validator.get("item_validator")
        return [
            validate_value(operations, adapter, item_validator, item)
            for item in value
        ]
    if not isinstance(value, str):
        raise ValueError(f"`{validator_name}` must be a string")
    normalized = normalize_value(value, validator)
    pattern = validator.get("regex")
    if pattern and re.fullmatch(pattern, normalized) is None:
        raise ValueError(f"`{value}` does not match `{validator_name}`")
    return normalized


def validator_type(
    operations: dict[str, Any], adapter: dict[str, Any], validator_name: str
) -> str:
    return str(resolve_validator(operations, adapter, validator_name).get("runtime_type"))


def placeholders_in_argv(argv: list[str]) -> list[tuple[str, str | None]]:
    found: list[tuple[str, str | None]] = []
    for token in argv:
        found.extend(PLACEHOLDER_RE.findall(token))
    return found


def validate_commands(operations: dict[str, Any], adapter: dict[str, Any]) -> None:
    command_specs = operations.get("commands", {})
    adapter_commands = adapter.get("commands", {})
    for name, spec in command_specs.items():
        if name not in adapter_commands:
            raise SystemExit(f"Adapter `{adapter['adapter']}` is missing command `{name}`")
        params = spec.get("params", {})
        steps = adapter_commands[name].get("steps", [])
        if not isinstance(steps, list) or not steps:
            raise SystemExit(f"Command `{name}` must have non-empty steps")
        for index, step in enumerate(steps, start=1):
            argv = step.get("argv")
            if not isinstance(argv, list) or not all(isinstance(item, str) for item in argv):
                raise SystemExit(f"Command `{name}` step {index} must have string argv")
            if len(argv) >= 2 and argv[0] in {"sh", "bash"} and argv[1] == "-c":
                raise SystemExit(f"Command `{name}` step {index} must not use shell strings")
            foreach = step.get("foreach")
            foreach_name = None
            if foreach is not None:
                foreach_param = foreach.get("param")
                foreach_name = foreach.get("as")
                if foreach_param not in params:
                    raise SystemExit(
                        f"Command `{name}` foreach param `{foreach_param}` is not declared"
                    )
                if not isinstance(foreach_name, str):
                    raise SystemExit(f"Command `{name}` foreach.as must be a string")
                if validator_type(operations, adapter, params[foreach_param]) != "list":
                    raise SystemExit(
                        f"Command `{name}` foreach param `{foreach_param}` must use a list validator"
                    )
            allowed = set(params)
            if foreach_name:
                allowed.add(foreach_name)
            placeholders = placeholders_in_argv(argv)
            unresolved = {name for name, _ in placeholders} - allowed
            if unresolved:
                raise SystemExit(
                    f"Command `{name}` step {index} has unresolved placeholders: {sorted(unresolved)}"
                )
            for placeholder_name, transform in placeholders:
                if not transform:
                    continue
                if transform != "contents":
                    raise SystemExit(
                        f"Command `{name}` step {index} has unsupported placeholder transform `{transform}`"
                    )
                if placeholder_name not in params:
                    raise SystemExit(
                        f"Command `{name}` step {index} uses file contents for non-param `{placeholder_name}`"
                    )
                if params[placeholder_name] != "body_file_path":
                    raise SystemExit(
                        f"Command `{name}` step {index} can only use :contents with body_file_path params"
                    )


def make_filter(recipe: str):
    match = re.fullmatch(r"(join_with|join_with_prefix|join_with_affixes)\((.*)\)", recipe)
    if not match:
        raise SystemExit(f"Unsupported formatter filter recipe `{recipe}`")
    function_name, raw_args = match.groups()
    kwargs: dict[str, str] = {}
    for key, value in re.findall(r"([A-Za-z_][A-Za-z0-9_]*)='([^']*)'", raw_args):
        kwargs[key] = value

    if function_name == "join_with":
        sep = kwargs.get("sep", " ")

        def join_with(items: list[str], sep: str = sep) -> str:
            return sep.join(items)

        return join_with

    sep = kwargs.get("sep", " ")
    prefix = kwargs.get("prefix", "")

    if function_name == "join_with_affixes":
        suffix = kwargs.get("suffix", "")

        def join_with_affixes(
            items: list[str],
            sep: str = sep,
            prefix: str = prefix,
            suffix: str = suffix,
        ) -> str:
            return sep.join(prefix + item + suffix for item in items)

        return join_with_affixes

    def join_with_prefix(items: list[str], sep: str = sep, prefix: str = prefix) -> str:
        return sep.join(prefix + item for item in items)

    return join_with_prefix


def formatter_environment(adapter: dict[str, Any]) -> Environment:
    env = Environment(undefined=StrictUndefined, autoescape=False)
    for filter_name, recipe in adapter.get("formatter_filters", {}).items():
        env.filters[filter_name] = make_filter(recipe)
    return env


def validate_formatters(operations: dict[str, Any], adapter: dict[str, Any]) -> None:
    formatter_specs = operations.get("formatters", {})
    adapter_formatters = adapter.get("formatters", {})
    env = formatter_environment(adapter)
    for name, spec in formatter_specs.items():
        if name not in adapter_formatters:
            raise SystemExit(f"Adapter `{adapter['adapter']}` is missing formatter `{name}`")
        template = adapter_formatters[name]
        ast = env.parse(template)
        declared = set(spec.get("params", {}))
        referenced = meta.find_undeclared_variables(ast)
        unknown = referenced - declared
        if unknown:
            raise SystemExit(
                f"Formatter `{name}` references undeclared params: {sorted(unknown)}"
            )
        collector = FilterCollector()
        collector.visit(ast)
        declared_filters = set(adapter.get("formatter_filters", {}))
        unknown_filters = collector.filters - declared_filters
        if unknown_filters:
            raise SystemExit(
                f"Formatter `{name}` uses undeclared filters: {sorted(unknown_filters)}"
            )


def validate_adapter(operations: dict[str, Any], adapter: dict[str, Any]) -> None:
    if "ticket_id" not in adapter.get("validators", {}):
        raise SystemExit(f"Adapter `{adapter['adapter']}` must define ticket_id")
    validate_commands(operations, adapter)
    validate_formatters(operations, adapter)


def has_runtime_placeholder(value: Any) -> bool:
    if isinstance(value, str):
        return "<" in value or ">" in value or value == "..."
    if isinstance(value, list):
        return any(has_runtime_placeholder(item) for item in value)
    return False


def validation_lines(
    operations: dict[str, Any], adapter: dict[str, Any], params: dict[str, str]
) -> str:
    lines = []
    for param, validator_name in params.items():
        validator = resolve_validator(operations, adapter, validator_name)
        runtime_type = validator.get("runtime_type")
        description = validator.get("description", "").strip()
        lines.append(
            f"- `{param}`: `{validator_name}` ({runtime_type}) - {description}"
        )
    return "\n".join(lines)


def substitute_token(token: str, values: dict[str, Any], foreach_name: str | None) -> str:
    def replacement(match: re.Match[str]) -> str:
        name = match.group(1)
        transform = match.group(2)
        if foreach_name and name == foreach_name:
            return f"<{foreach_name}>"
        if transform == "contents":
            return f"<contents of validated {name}>"
        value = values.get(name, f"<{name}>")
        if isinstance(value, list):
            return f"<{name}>"
        return str(value)

    return PLACEHOLDER_RE.sub(replacement, token)


def command_recipe(
    operations: dict[str, Any],
    adapter: dict[str, Any],
    name: str,
    values: dict[str, Any],
) -> str:
    command = adapter["commands"][name]
    lines = [f"Command `{name}`:"]
    for index, step in enumerate(command["steps"], start=1):
        foreach = step.get("foreach")
        foreach_name = foreach.get("as") if foreach else None
        rendered_argv = [
            substitute_token(token, values, foreach_name) for token in step["argv"]
        ]
        content_params = sorted(
            {
                name
                for token in step["argv"]
                for name, transform in PLACEHOLDER_RE.findall(token)
                if transform == "contents"
            }
        )
        content_note = ""
        if content_params:
            joined = ", ".join(f"`{param}`" for param in content_params)
            content_note = (
                f" Read {joined} after path validation and pass the full file contents "
                "as that argv element."
            )
        if foreach:
            lines.append(
                f"{index}. For each item in `{foreach['param']}` as `{foreach_name}`:"
            )
            lines.append(f"   `argv`: `{json.dumps(rendered_argv)}`{content_note}")
        else:
            lines.append(f"{index}. `argv`: `{json.dumps(rendered_argv)}`{content_note}")
    return "\n".join(lines)


def formatter_recipe(
    operations: dict[str, Any],
    adapter: dict[str, Any],
    name: str,
) -> str:
    params = operations["formatters"][name].get("params", {})
    template = adapter["formatters"][name].rstrip()
    return "\n".join(
        [
            f"Formatter `{name}`:",
            "",
            "```jinja",
            template,
            "```",
            "",
            "Parameters:",
            validation_lines(operations, adapter, params),
        ]
    )


def render_formatter(
    operations: dict[str, Any],
    adapter: dict[str, Any],
    name: str,
    values: dict[str, Any],
) -> str:
    params = operations["formatters"][name].get("params", {})
    missing = set(params) - set(values)
    if missing:
        raise ValueError(f"Formatter `{name}` missing params: {sorted(missing)}")
    if any(has_runtime_placeholder(value) for value in values.values()):
        return formatter_recipe(operations, adapter, name)
    normalized = {
        param: validate_value(operations, adapter, validator, values[param])
        for param, validator in params.items()
    }
    env = formatter_environment(adapter)
    return env.from_string(adapter["formatters"][name]).render(**normalized).rstrip()


def yaml_string(value: str) -> str:
    return json.dumps(value)


def skill_frontmatter(
    runtime: str,
    name: str,
    description: str,
    argument_hint: str,
    allow_implicit_invocation: bool,
) -> str:
    del allow_implicit_invocation
    lines = [
        "---",
        f"name: {yaml_string(name)}",
        f"description: {yaml_string(description)}",
    ]
    if runtime == "claude":
        lines.extend(
            [
                "disable-model-invocation: true",
                f"argument-hint: {yaml_string(argument_hint)}",
            ]
        )
    lines.append("---")
    return "\n".join(lines)


def reviewer_setup(runtime: str, runtime_config: dict[str, Any]) -> str:
    reviewer = runtime_config["reviewer"]
    lines = [reviewer["install_prerequisite"].strip(), "", reviewer["mechanism"].strip()]
    if runtime == "codex":
        bundled = reviewer.get("bundled_mcp_server", {})
        if not bundled.get("verified_for_plugin_bundle", False):
            lines.extend(
                [
                    "",
                    "This plugin does not assume bundled MCP server activation. If the `Agent` MCP tool is not visible, stop and ask the user to run the setup command above.",
                ]
            )
    return "\n".join(lines)


def reviewer_call_recipe(runtime: str, runtime_config: dict[str, Any], kind: str) -> str:
    reviewer = runtime_config["reviewer"]
    if runtime == "claude":
        return "\n".join(
            [
                f"Invoke MCP tool `{reviewer['tool_name']}`:",
                "",
                "- `prompt`: the review prompt with concrete scope and context",
                "- `cwd`: project root",
                "",
                f"Save the returned `threadId`. Continue follow-up rounds with `{reviewer['reply_tool_name']}` using that `threadId`.",
            ]
        )
    return "\n".join(
        [
            f"Invoke MCP tool `{reviewer['tool_name']}` from the `claude-code` server:",
            "",
            f"- `description`: `{kind}`",
            "- `prompt`: the review prompt with concrete scope and context",
            "- `run_in_background`: `false` unless the user explicitly asked for background work",
            "",
            "If the tool is unavailable, stop and ask the user to configure `codex mcp add claude-code -- claude mcp serve`.",
        ]
    )


def build_environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_ROOT),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env


def plugin_name(plugin_id: str, adapter_name: str) -> str:
    return f"{plugin_id}-{adapter_name}"


def plugin_description(adapter_name: str) -> str:
    return f"Epic workflow + adversarial review, {adapter_name}-flavored."


def brand_color(adapter_name: str) -> str:
    return "#24292F" if adapter_name == "github" else "#345995"


def validate_registry(registry: dict[str, Any]) -> None:
    if registry.get("schema_version") != 2:
        raise SystemExit("registry.yaml schema_version must be 2")
    if not registry.get("plugins"):
        raise SystemExit("registry.yaml must declare plugins")
    matrix = registry.get("runtime_adapter_matrix", {})
    if not matrix.get("runtimes") or not matrix.get("adapters"):
        raise SystemExit("registry.yaml must declare runtime_adapter_matrix")
    for plugin in registry["plugins"]:
        for skill in plugin.get("skills", []):
            path = TEMPLATE_ROOT / "skills" / f"{skill}.md.j2"
            if not path.exists():
                raise SystemExit(f"Missing skill template for `{skill}`")


def base_context(
    registry: dict[str, Any],
    operations: dict[str, Any],
    runtime_name: str,
    runtime_config: dict[str, Any],
    adapter_name: str,
    adapter: dict[str, Any],
) -> dict[str, Any]:
    def cmd(name: str, **values: Any) -> str:
        return command_recipe(operations, adapter, name, values)

    def fmt(name: str, **values: Any) -> str:
        return render_formatter(operations, adapter, name, values)

    def validation_instructions_for(name: str) -> str:
        if name in operations["commands"]:
            params = operations["commands"][name].get("params", {})
        elif name in operations["formatters"]:
            params = operations["formatters"][name].get("params", {})
        else:
            raise ValueError(f"Unknown operation `{name}`")
        return validation_lines(operations, adapter, params)

    def registry_rules_for(
        phase: str, categories: list[str] | None = None
    ) -> str:
        return render_rule_list(registry, runtime_name, phase, categories)

    return {
        "adapter": adapter_name,
        "adapter_config": adapter,
        "agent_descriptions": registry.get("agent_descriptions", {}),
        "brand_color": brand_color(adapter_name),
        "cmd": cmd,
        "descriptions": registry.get("skill_descriptions", {}),
        "fmt": fmt,
        "fragments": adapter.get("fragments", {}),
        "generated_notice": GENERATED_NOTICE,
        "marketplace": registry["marketplace"],
        "registry_rules_for": registry_rules_for,
        "reviewer": runtime_config.get("reviewer", {}),
        "reviewer_call_recipe": lambda kind: reviewer_call_recipe(
            runtime_name, runtime_config, kind
        ),
        "reviewer_setup": lambda: reviewer_setup(runtime_name, runtime_config),
        "runtime": runtime_name,
        "runtime_config": runtime_config,
        "skill_frontmatter": lambda **kwargs: skill_frontmatter(
            runtime_name, **kwargs
        ),
        "teammate": runtime_config.get("teammate", {}),
        "validation_instructions_for": validation_instructions_for,
        "vocab": adapter.get("vocab", {}),
    }


def render_template(env: Environment, template_name: str, context: dict[str, Any]) -> str:
    rendered = env.get_template(template_name).render(**context).rstrip() + "\n"
    if "[[" in rendered or "]]" in rendered:
        raise SystemExit(f"Legacy placeholder marker remains in {template_name}")
    return rendered


def render_all(
    registry: dict[str, Any],
    operations: dict[str, Any],
    adapters: dict[str, dict[str, Any]],
    runtimes: dict[str, dict[str, Any]],
) -> list[RenderedFile]:
    env = build_environment()
    rendered: list[RenderedFile] = []
    marketplace = registry["marketplace"]

    for plugin in registry["plugins"]:
        plugin_id = plugin["id"]
        for runtime_name in registry["runtime_adapter_matrix"]["runtimes"]:
            runtime_config = runtimes[runtime_name]
            for adapter_name in registry["runtime_adapter_matrix"]["adapters"]:
                adapter = adapters[adapter_name]
                name = plugin_name(plugin_id, adapter_name)
                plugin_root = REPO_ROOT / "plugins" / runtime_name / name
                context = base_context(
                    registry,
                    operations,
                    runtime_name,
                    runtime_config,
                    adapter_name,
                    adapter,
                )
                context.update({"plugin_name": name, "plugin": plugin})

                for skill_name in plugin["skills"]:
                    skill_context = dict(context)
                    skill_context["skill_name"] = skill_name
                    output = plugin_root / "skills" / skill_name / "SKILL.md"
                    rendered.append(
                        RenderedFile(
                            f"skills/{skill_name}.md.j2",
                            output,
                            render_template(
                                env, f"skills/{skill_name}.md.j2", skill_context
                            ),
                        )
                    )
                    if runtime_name == "codex":
                        metadata_output = (
                            plugin_root
                            / "skills"
                            / skill_name
                            / "agents"
                            / "openai.yaml"
                        )
                        rendered.append(
                            RenderedFile(
                                "manifests/openai.yaml.j2",
                                metadata_output,
                                render_template(
                                    env, "manifests/openai.yaml.j2", skill_context
                                ),
                            )
                        )

                for agent_name in plugin.get("agents_for_runtimes", {}).get(
                    runtime_name, []
                ):
                    output = plugin_root / "agents" / f"{agent_name}.md"
                    rendered.append(
                        RenderedFile(
                            f"agents/{agent_name}.md.j2",
                            output,
                            render_template(env, f"agents/{agent_name}.md.j2", context),
                        )
                    )

                if runtime_name == "claude":
                    manifest_output = plugin_root / ".claude-plugin" / "plugin.json"
                    manifest_template = "manifests/claude-plugin.json.j2"
                else:
                    manifest_output = plugin_root / ".codex-plugin" / "plugin.json"
                    manifest_template = "manifests/codex-plugin.json.j2"
                rendered.append(
                    RenderedFile(
                        manifest_template,
                        manifest_output,
                        render_template(env, manifest_template, context),
                    )
                )

                bundled = runtime_config.get("reviewer", {}).get(
                    "bundled_mcp_server", {}
                )
                if runtime_name == "codex" and bundled.get(
                    "verified_for_plugin_bundle", False
                ):
                    rendered.append(
                        RenderedFile(
                            "manifests/mcp.json.j2",
                            plugin_root / ".mcp.json",
                            render_template(env, "manifests/mcp.json.j2", context),
                        )
                    )

    claude_plugins = [
        {
            "name": plugin_name("epic-workflow", adapter_name),
            "source": f"./plugins/claude/{plugin_name('epic-workflow', adapter_name)}",
            "description": plugin_description(adapter_name),
            "tags": ["workflow", adapter_name, "agent-team"],
        }
        for adapter_name in registry["runtime_adapter_matrix"]["adapters"]
    ]
    codex_plugins = [
        {
            "name": plugin_name("epic-workflow", adapter_name),
            "source": f"./plugins/codex/{plugin_name('epic-workflow', adapter_name)}",
        }
        for adapter_name in registry["runtime_adapter_matrix"]["adapters"]
    ]
    rendered.append(
        RenderedFile(
            "manifests/claude-marketplace.json.j2",
            REPO_ROOT / ".claude-plugin" / "marketplace.json",
            render_template(
                env,
                "manifests/claude-marketplace.json.j2",
                {"marketplace": marketplace, "plugins": claude_plugins},
            ),
        )
    )
    rendered.append(
        RenderedFile(
            "manifests/codex-marketplace.json.j2",
            REPO_ROOT / ".agents" / "plugins" / "marketplace.json",
            render_template(
                env,
                "manifests/codex-marketplace.json.j2",
                {"marketplace": marketplace, "plugins": codex_plugins},
            ),
        )
    )
    rendered.append(
        RenderedFile(
            "docs/process/improvements.md.j2",
            REPO_ROOT / "docs" / "process" / "improvements.md",
            render_template(
                env,
                "docs/process/improvements.md.j2",
                {
                    "active_rules_table": lambda: render_active_rules_table(registry),
                    "generated_notice": GENERATED_NOTICE,
                    "registry_reference": lambda: render_registry_reference(registry),
                },
            ),
        )
    )
    return rendered


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def write_rendered_file(path: Path, content: str, check: bool) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == content:
            return False
    if check:
        return True
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    return True


def run_golden_tests(operations: dict[str, Any], adapters: dict[str, dict[str, Any]]) -> None:
    github = adapters["github"]
    tkt = adapters["tkt"]

    assert validate_value(operations, github, "ticket_id", "#42") == "42"
    try:
        validate_value(operations, github, "shell_safe_title", "bad $ title")
    except ValueError:
        pass
    else:
        raise AssertionError("shell_safe_title accepted a shell metacharacter")

    github_body = render_formatter(
        operations,
        github,
        "review_body",
        {
            "title": "Review title",
            "summary": "Implemented the thing.",
            "linked_ticket_ids": ["42", "55"],
            "branch_ref": "feature/auth",
        },
    )
    assert "#42, #55" in github_body
    assert "Closes #42, #55" in github_body

    tkt_dependency = render_formatter(
        operations,
        tkt,
        "dependency_annotation",
        {"ticket_ids": ["AUTH-42", "AUTH-55"]},
    )
    assert tkt_dependency == "Depends on AUTH-42, AUTH-55"

    try:
        render_formatter(
            operations,
            github,
            "dependency_annotation",
            {"ticket_ids": []},
        )
    except ValueError:
        pass
    else:
        raise AssertionError("empty ticket_id_list was accepted")

    tkt_publish = command_recipe(
        operations,
        tkt,
        "work_publish",
        {
            "title": "Review title",
            "body_file": ".agent-skills-tmp/review.md",
            "linked_ticket_ids": ["AUTH-42"],
        },
    )
    assert "For each item in `linked_ticket_ids` as `ticket_id`" in tkt_publish
    assert "sh -c" not in tkt_publish
    assert "printf '%q'" not in tkt_publish


def validate_rendered_outputs(rendered: list[RenderedFile]) -> None:
    banned = ["sh -c", "printf '%q'", "shlex.quote"]
    for item in rendered:
        for needle in banned:
            if needle in item.content:
                raise SystemExit(f"{item.output.relative_to(REPO_ROOT)} contains `{needle}`")
        if item.output.suffix == ".json":
            json.loads(item.content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Check for stale generated files")
    args = parser.parse_args()

    operations = load_yaml(OPERATIONS_PATH)
    registry = load_yaml(REGISTRY_PATH)
    adapters = load_named_yaml(ADAPTERS_DIR, "adapter")
    runtimes = load_named_yaml(RUNTIMES_DIR, "runtime")

    validate_registry(registry)
    for adapter in adapters.values():
        validate_adapter(operations, adapter)
    run_golden_tests(operations, adapters)

    rendered = render_all(registry, operations, adapters, runtimes)
    validate_rendered_outputs(rendered)

    changed: list[Path] = []
    for item in rendered:
        if write_rendered_file(item.output, item.content, check=args.check):
            changed.append(item.output)

    if args.check and changed:
        print("Generated files are stale:")
        for path in changed:
            print(f"- {path.relative_to(REPO_ROOT)}")
        return 1

    action = "Checked" if args.check else "Rendered"
    print(f"{action} {len(rendered)} file(s).")
    if changed and not args.check:
        for path in changed:
            print(f"- {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
